In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x_in = np.array([[
  [[2], [1], [2], [0], [1]],
  [[1], [3], [2], [2], [3]],
  [[1], [1], [3], [3], [0]],
  [[2], [2], [0], [1], [1]],
  [[0], [0], [3], [1], [2]], ]])

## conv2d

In [3]:
kernel_in = np.array([
 [ [[2, 0.1]], [[3, 0.2]] ],
 [ [[0, 0.3]],[[1, 0.4]] ], ])

In [4]:
x = tf.constant(x_in, dtype=tf.float32)

In [5]:
print(x.shape)

(1, 5, 5, 1)


In [6]:
kernel = tf.constant(kernel_in, dtype=tf.float32)

In [7]:
print(kernel.shape)

(2, 2, 1, 2)


In [8]:
x_out = tf.nn.conv2d(x, kernel, strides=[1, 1, 1, 1], padding='VALID')

In [9]:
print(x_out)

tf.Tensor(
[[[[10.         1.9      ]
   [10.         2.2      ]
   [ 6.         1.6      ]
   [ 6.         2.       ]]

  [[12.         1.4      ]
   [15.         2.2      ]
   [13.         2.7      ]
   [13.         1.7      ]]

  [[ 7.         1.7      ]
   [11.         1.3000001]
   [16.         1.3      ]
   [ 7.         1.       ]]

  [[10.         0.6      ]
   [ 7.         1.4000001]
   [ 4.         1.5      ]
   [ 7.         1.4      ]]]], shape=(1, 4, 4, 2), dtype=float32)


## max_pool

In [10]:
x_out = tf.nn.max_pool(x, ksize=[1,2,2,1], strides=[1,1,1,1], padding="VALID")

In [11]:
print(x_out)

tf.Tensor(
[[[[3.]
   [3.]
   [2.]
   [3.]]

  [[3.]
   [3.]
   [3.]
   [3.]]

  [[2.]
   [3.]
   [3.]
   [3.]]

  [[2.]
   [3.]
   [3.]
   [2.]]]], shape=(1, 4, 4, 1), dtype=float32)


## Dropout

In [13]:
data = np.arange(10).reshape(5, 2).astype(np.float32)
print(data)

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [14]:
tf.random.set_seed(0)
layer = tf.keras.layers.Dropout(.2, input_shape=(2,))

In [15]:
outputs = layer(data, training=True)
print(outputs)

tf.Tensor(
[[ 0.    1.25]
 [ 2.5   3.75]
 [ 5.    6.25]
 [ 7.5   8.75]
 [10.    0.  ]], shape=(5, 2), dtype=float32)


In [16]:
outputs = layer(data, training=True)
print(outputs)

tf.Tensor(
[[ 0.    1.25]
 [ 2.5   3.75]
 [ 5.    6.25]
 [ 0.    8.75]
 [10.   11.25]], shape=(5, 2), dtype=float32)


In [17]:
outputs = layer(data, training=True)
print(outputs)

tf.Tensor(
[[ 0.    1.25]
 [ 2.5   3.75]
 [ 5.    0.  ]
 [ 7.5   8.75]
 [10.   11.25]], shape=(5, 2), dtype=float32)
